### PR TITLE
Fix loading of Rest_in_Place in Rails 5 with turbolinks

### PR DESCRIPTION
**Pull request by tgds**
Turbolinks now fire turbolinks:load in Rails 5 and page:load event is not fired anymore.

### CODE REVIEW

**Comment by jmaziarz** [comment]
+1 What are the chances of merging this?

**Comment by janv** [comment]
Zero, for the reasons stated in #67 and also the fact that this PR replaced the README.md

**Comment by tgds** [comment]
Whoops, didn't notice I included the readme.

**Comment by janv** [comment]
If you need a maintained, production ready alternative to this, check out https://github.com/bernat/best_in_place

**Pull request closed without merging**
